// ============================================================
// Bot conversation state machine
// Pure functions — no side effects, easy to test.
//
// NOTE: This engine tracks conversation STATE only.
// Patient-facing responses are generated by the AI (ai-chat.ts).
// The response strings returned here are either:
//   - AI context markers (__FETCH_*) for data fetching
//   - Fallback messages used ONLY when AI is unavailable
// ============================================================
import type { BotContext, BotState, BotIntent } from '@/lib/types/whatsapp.types'
import { classifyIntent } from './intent-classifier'
import { R } from './responses'
import { SEED_PATIENTS, SEED_SPECIALTIES, SEED_PROFESSIONALS } from '@/lib/data/seed'

export interface EngineResult {
  newContext: BotContext
  responses: string[]    // fallback messages or __FETCH_* markers
  shouldEndSession: boolean
}

// ── Natural language matching helpers ──────────────────────────

// Strip accents for comparison (e.g., "Kinesiología" → "Kinesiologia")
function normalize(text: string): string {
  return text.normalize('NFD').replace(/[̀-ͯ]/g, '')
}

// Words that indicate the user is asking a question or chatting, not selecting
const QUESTION_MARKERS = [
  'quien', 'quién', 'quienes', 'quiénes', 'cual', 'cuál', 'cuales', 'cuáles',
  'que ', 'qué ', 'como ', 'cómo ', 'cuando', 'cuándo', 'donde', 'dónde',
  'decime', 'decirme', 'decí', 'deci', 'dime', 'quiero', 'quisiera', 'me gustaria',
  'me gustaría', 'podés', 'podes', 'podrías', 'podrias', 'pueden', 'podrian',
  'consulta', 'quisiera', 'necesito', 'que cubre', 'que atiende', 'atienden',
  'cubren', 'cuales son', 'cuáles son', 'que hacen', 'qué hacen',
  'info', 'informacion', 'información', 'detalles', 'mas info', 'más info',
]

function isFreeTextQuestion(text: string): boolean {
  const lower = text.toLowerCase().trim()
  // Long messages (>4 words) are almost always questions or chat, not selections
  const wordCount = lower.split(/\s+/).length
  if (wordCount > 4) return true
  // Check for question markers
  for (const marker of QUESTION_MARKERS) {
    if (lower.includes(marker)) return true
  }
  return false
}

function matchByIndexOrName(
  text: string,
  items: string[]
): number | null {
  // Try number first
  const idx = parseInt(text) - 1
  if (!isNaN(idx) && idx >= 0 && idx < items.length) return idx

  const lower = normalize(text.toLowerCase().trim())
  const lowerWords = lower.split(/\s+/).filter(w => w.length >= 3)

  for (let i = 0; i < items.length; i++) {
    const itemLower = normalize(items[i].toLowerCase())
    // Extract just the name part (before any parenthetical specialty)
    // to prevent "odontologia" from matching "Denise (Odontologia)"
    const nameOnly = itemLower.replace(/\s*\(.*\)\s*$/, '').trim()

    // Check if the user's text matches the NAME part (not just the specialty)
    if (nameOnly.length > 0 && nameOnly.includes(lower)) return i
    // Also check full item for items without parentheses
    if (nameOnly === itemLower && itemLower.includes(lower)) return i
    // Check if any word from the user's text (3+ chars) is in the name
    // e.g., "con denise" should match "Denise Rodsevich" because "denise" is in it
    for (const w of lowerWords) {
      if (nameOnly.includes(w)) return i
    }
  }

  // Try if any item name is contained in the user's text
  for (let i = 0; i < items.length; i++) {
    const itemLower = normalize(items[i].toLowerCase())
    const nameOnly = itemLower.replace(/\s*\(.*\)\s*$/, '').trim()
    if (lower.includes(itemLower) || (nameOnly.length > 0 && lower.includes(nameOnly))) return i
    // Also check individual word matches (reverse direction)
    const nameWords = nameOnly.split(/\s+/).filter(w => w.length >= 3)
    for (const nw of nameWords) {
      if (lower.includes(nw)) return i
    }
  }

  return null
}

function matchByIndexOrLabel(
  text: string,
  items: Array<{ label: string }>
): number | null {
  // Try number first
  const idx = parseInt(text) - 1
  if (!isNaN(idx) && idx >= 0 && idx < items.length) return idx

  // Try matching words in the label (e.g., "Lun 15/05" → match "lun" or "15")
  const lower = text.toLowerCase().trim()
  for (let i = 0; i < items.length; i++) {
    const label = items[i].label.toLowerCase()
    // Check if any word from user input (2+ chars) appears in the label
    const words = lower.split(/\s+/).filter(w => w.length >= 2)
    if (words.some(w => label.includes(w))) return i
    // Also check if the label is contained in user text
    if (lower.includes(label)) return i
  }

  return null
}

// ── Helpers ─────────────────────────────────────────────────

function findPatientByName(text: string) {
  const lower = text.toLowerCase()
  return SEED_PATIENTS.find(p =>
    lower.includes(p.first_name.toLowerCase()) || lower.includes(p.last_name.toLowerCase())
  )
}

function makeContext(phone: string, overrides: Partial<BotContext> = {}): BotContext {
  return {
    phone,
    patientId: null,
    patientName: null,
    pendingPhone: null,
    pendingDni: null,
    state: 'idle',
    selectedSpecialty: null,
    selectedProfessional: null,
    selectedDate: null,
    selectedTime: null,
    selectedAppointmentId: null,
    lastMessageAt: new Date().toISOString(),
    messageCount: 0,
    isKnownPatient: false,
    ...overrides,
  }
}

// ── Main state machine ───────────────────────────────────────
export function processMessage(
  incomingText: string,
  currentContext: BotContext | null,
  pushName?: string,
): EngineResult {
  const phone = currentContext?.phone ?? ''
  const ctx = currentContext ?? makeContext(phone)
  const text = incomingText.trim()
  const intent = classifyIntent(text)

  const next = { ...ctx, messageCount: ctx.messageCount + 1, lastMessageAt: new Date().toISOString() }

  // Helpers used across states
  const hasAppts = (next.upcomingAppointments?.length ?? 0) > 0

  // Global overrides
  if (text.toLowerCase() === 'menú' || text.toLowerCase() === 'menu') {
    if (next.patientName) {
      next.state = 'main_menu'
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }
  }
  const BOOKING_STATES: BotState[] = ['booking_specialty','booking_professional','booking_date','booking_slots','booking_time','booking_confirm','cancel_select','cancel_confirm']
  if (intent === 'ask_human' && !BOOKING_STATES.includes(ctx.state)) {
    next.state = 'human_handoff'
    return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
  }
  if (intent === 'thanks' && !BOOKING_STATES.includes(ctx.state) && ctx.state !== 'nps_survey') {
    return { newContext: { ...next, state: 'closed' }, responses: ['__AI_GENERATE__'], shouldEndSession: true }
  }

  switch (ctx.state) {
    case 'idle':
    case 'closed':
    case 'greeting': {
      if (ctx.isKnownPatient && ctx.patientName) {
        next.state = 'main_menu'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      next.state = 'identify_patient'
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'identify_patient': {
      // Check if the user sounds like they want to book, not give their name
      // "quiero sacar un turno", "necesito un turno", etc. → redirect to booking
      const bookingKeywords = ['turno', 'sacar', 'reservar', 'agendar', 'consulta']
      const bookingMatch = bookingKeywords.filter(k => text.toLowerCase().includes(k))
      if (bookingMatch.length >= 2 || text.toLowerCase().includes('sacar un turno') || intent === 'book_appointment') {
        if (ctx.isKnownPatient && ctx.patientName) {
          next.state = 'main_menu'
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        // Ask for name naturally
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const words = text.trim().split(/\s+/).filter(w => w.length > 0)
      if (words.length < 2) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      // Skip if text looks like a question or general statement (not a name)
      if (isFreeTextQuestion(text)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const fullName = words.slice(0, 3).join(' ')
      next.patientName = fullName
      next.pendingPhone = phone
      next.state = 'ask_dni'
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'ask_dni': {
      const skip = ['omitir', 'skip', 'no', '-', 'no tengo'].includes(text.toLowerCase().trim())
      const digits = text.replace(/\D/g, '')
      if (!skip && (digits.length < 7 || digits.length > 9)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      next.pendingDni = skip ? null : digits
      next.state = 'main_menu'
      next.isKnownPatient = true
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'main_menu': {
      // Purely intent-driven — no number mapping.
      // The AI handles all responses; numbers are just raw text that
      // the AI can interpret conversationally if needed.
      const resolved = intent

      if (resolved === 'book_appointment') {
        // Clear stale booking data from previous conversations
        next.selectedSpecialty = null
        next.selectedProfessional = null
        next.selectedDate = null
        next.selectedTime = null
        next.selectedAppointmentId = null
        next.availableDatesList = undefined
        next.availableSlotsList = undefined

        // Check if user already mentioned a specialty in this message
        // e.g. "para la semana entrante que tenes en odontologia?"
        const specList = ctx.specialties?.length ? ctx.specialties : SEED_SPECIALTIES.map(s => s.name)
        const specIdx = matchByIndexOrName(text, specList)
        if (specIdx !== null) {
          next.selectedSpecialty = specList[specIdx]
          next.state = 'booking_professional'
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }

        next.state = 'booking_specialty'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (resolved === 'cancel_appointment') {
        const appts = next.upcomingAppointments ?? []
        if (!appts.length) {
          next.state = 'no_appointments'
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        next.state = 'cancel_select'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (resolved === 'view_appointments') {
        const appts = next.upcomingAppointments ?? []
        if (!appts.length) {
          next.state = 'no_appointments'
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        next.state = 'view_appointments'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (resolved === 'reschedule') {
        const appts = next.upcomingAppointments ?? []
        if (!appts.length) {
          next.state = 'no_appointments'
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        next.state = 'reschedule'
        if (appts.length === 1) {
          const a = appts[0]
          next.selectedAppointmentId = a.id
          next.selectedDate = a.date
          next.selectedTime = a.time
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (resolved === 'ask_human') {
        next.state = 'human_handoff'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'no_appointments': {
      const t = text.toLowerCase().trim()
      if (['1', 'si', 'sí', 's', 'dale', 'ok'].includes(t)) {
        next.state = 'booking_specialty'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (['2', 'no', 'nop', 'gracias', 'no gracias'].includes(t)) {
        next.state = 'closed'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: true }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'booking_specialty': {
      // Try to match a specialty name first — even in free-text questions
      // like "para la semana entrante que tenes en odontologia?"
      const specList = ctx.specialties?.length ? ctx.specialties : SEED_SPECIALTIES.map(s => s.name)
      const matchedIdx = matchByIndexOrName(text, specList)
      if (matchedIdx !== null) {
        next.selectedSpecialty = specList[matchedIdx]
        next.state = 'booking_professional'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      // No specialty matched — if it's a question, let AI handle it
      if (isFreeTextQuestion(text)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'booking_professional': {
      const lower = text.toLowerCase()
      // If the user is asking a question, let AI handle it
      if (isFreeTextQuestion(text)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      // Short affirmatives ("si", "dale", "ok") in this state mean the user
      // is confirming the previously mentioned professional, but we don't know
      // which one — let the AI handle it
      const AFFIRMATIVES = ['si', 'sí', 's', 'ok', 'okay', 'dale', 'de una', 'da']
      if (AFFIRMATIVES.includes(lower)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const profs = ctx.professionals?.length ? ctx.professionals : SEED_PROFESSIONALS.map(p => p.full_name)
      const isNoPreference = text === '0' ||
        lower.includes('sin') || lower.includes('preferencia') ||
        lower.includes('cualquiera') || lower.includes('indistinto') ||
        lower.includes('me da igual') || lower.includes('no importa') ||
        lower.includes('no tengo preferencia')

      if (isNoPreference) {
        next.selectedProfessional = 'Sin preferencia'
        next.state = 'booking_date'
        return { newContext: next, responses: ['__FETCH_DATES__'], shouldEndSession: false }
      }

      const matchedIdx = matchByIndexOrName(text, profs)
      if (matchedIdx === null) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      next.selectedProfessional = profs[matchedIdx]
      next.state = 'booking_date'
      return { newContext: next, responses: ['__FETCH_DATES__'], shouldEndSession: false }
    }

    case 'booking_date': {
      // Free-text questions shouldn't match date labels — let AI handle it
      if (isFreeTextQuestion(text)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const dates = ctx.availableDatesList ?? []
      if (dates.length === 0) {
        return { newContext: next, responses: ['__FETCH_DATES__'], shouldEndSession: false }
      }
      const matchedIdx = matchByIndexOrLabel(text, dates)
      if (matchedIdx === null) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      next.selectedDate = dates[matchedIdx].date
      next.availableDatesList = undefined
      next.state = 'booking_slots'
      return { newContext: next, responses: ['__FETCH_SLOTS__'], shouldEndSession: false }
    }

    case 'booking_slots': {
      // Free-text questions shouldn't match slot labels — let AI handle it
      if (isFreeTextQuestion(text)) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const slots = ctx.availableSlotsList ?? []
      if (slots.length === 0) {
        next.state = 'booking_date'
        next.availableDatesList = undefined
        return { newContext: next, responses: ['__FETCH_DATES__'], shouldEndSession: false }
      }
      const matchedIdx = matchByIndexOrLabel(text, slots)
      if (matchedIdx === null) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const slot = slots[matchedIdx]
      next.selectedDate = slot.date
      next.selectedTime = slot.time
      next.availableSlotsList = undefined
      next.state = 'booking_confirm'
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'booking_confirm': {
      const t = text.toLowerCase().trim()
      // Check if the text CONTAINS any confirmation word (flexible matching)
      const confirmWords = ['si', 'sí', 's', 'ok', 'dale', 'confirmo', 'confirmar', 'confirm', 'okay', 'genial', 'perfecto', 'buenísimo', 'buenisimo', 'correcto', 'claro', 'ya', 'de acuerdo', 'joya', 'agenda', 'reserva']
      const denyWords = ['no', 'nop', 'nel', 'cancelar', 'atrás', 'atras', 'volver', 'cancel']
      const isConfirm = confirmWords.some(w => t.includes(w))
      const isDeny    = denyWords.some(w => t === w || t.includes(` ${w} `) || t.startsWith(`${w} `) || t.endsWith(` ${w}`))
      if (isConfirm) {
        next.state = 'booking_done'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (isDeny) {
        next.state = 'main_menu'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'cancel_select': {
      const appts = next.upcomingAppointments ?? []
      // Try natural language: match against appointment professional/date/specialty
      const lower = text.toLowerCase().trim()
      let matchedIdx: number | null = parseInt(text) - 1
      if (isNaN(matchedIdx) || matchedIdx < 0 || matchedIdx >= appts.length) {
        matchedIdx = null
        for (let i = 0; i < appts.length; i++) {
          const a = appts[i]
          if (lower.includes(a.professional.toLowerCase()) ||
              lower.includes(a.date) ||
              lower.includes(a.specialty.toLowerCase())) {
            matchedIdx = i
            break
          }
        }
      }
      if (matchedIdx === null) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const appt = appts[matchedIdx]
      next.selectedDate = appt.date
      next.selectedTime = appt.time
      next.selectedAppointmentId = appt.id
      next.state = 'cancel_confirm'
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'cancel_confirm': {
      const t = text.toLowerCase().trim()
      const isConfirm = ['1','si','sí','s','ok','dale','confirmo'].includes(t)
      const isDeny    = ['2','no','nop','nel','atrás','atras','volver'].includes(t)
      if (isConfirm) {
        next.state = 'main_menu'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (isDeny) {
        next.state = 'main_menu'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'reschedule': {
      if (next.selectedAppointmentId) {
        const t = text.toLowerCase().trim()
        if (['1','si','sí','s','ok','dale'].includes(t)) {
          next.state = 'booking_specialty'
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        if (['2','no','nop','nel','volver'].includes(t)) {
          next.state = 'main_menu'
          next.selectedAppointmentId = null
          return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
        }
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const appts = next.upcomingAppointments ?? []
      if (!appts.length) {
        next.state = 'no_appointments'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      // Try natural language matching first
      const lower = text.toLowerCase().trim()
      let matchedIdx: number | null = parseInt(text) - 1
      if (isNaN(matchedIdx) || matchedIdx < 0 || matchedIdx >= appts.length) {
        matchedIdx = null
        for (let i = 0; i < appts.length; i++) {
          const a = appts[i]
          if (lower.includes(a.professional.toLowerCase()) ||
              lower.includes(a.date) ||
              lower.includes(a.specialty.toLowerCase())) {
            matchedIdx = i
            break
          }
        }
      }
      if (matchedIdx === null) {
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      const appt = appts[matchedIdx]
      next.selectedAppointmentId = appt.id
      next.selectedDate = appt.date
      next.selectedTime = appt.time
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'view_appointments': {
      const t = text.toLowerCase().trim()
      const cancelMatch = ['cancelar', 'anular', 'borrar', 'eliminar', 'cancel']
      const rescheduleMatch = ['reprogramar', 'cambiar', 'modificar', 'mover']
      const backMatch = ['menú', 'menu', 'volver', 'atrás', 'atras', 'volver al menu', 'volver al menú']
      if (cancelMatch.some(w => t.includes(w)) || intent === 'cancel_appointment') {
        next.state = 'cancel_select'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (rescheduleMatch.some(w => t.includes(w)) || intent === 'reschedule') {
        next.state = 'reschedule'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      if (backMatch.some(w => t.includes(w))) {
        next.state = 'main_menu'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    case 'nps_survey': {
      const score = parseInt(text)
      if (!isNaN(score) && score >= 0 && score <= 10) {
        next.state = 'closed'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: true }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }

    default: {
      next.state = 'idle'
      if (next.isKnownPatient && next.patientName) {
        next.state = 'main_menu'
        return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
      }
      return { newContext: next, responses: ['__AI_GENERATE__'], shouldEndSession: false }
    }
  }
}

export function createInitialContext(phone: string): BotContext {
  return makeContext(phone)
}

export function makeMessage(
  direction: 'inbound' | 'outbound',
  text: string,
  phone: string,
  state?: BotState,
  intent?: BotIntent,
) {
  return {
    id: crypto.randomUUID(),
    phone,
    direction,
    text,
    timestamp: new Date().toISOString(),
    botState: state,
    intent,
  }
}
